//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drive.Client.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drive.Client.Resources.Resx.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more accurate results.
        /// </summary>
        public static string AccurateResults {
            get {
                return ResourceManager.GetString("AccurateResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual information as of 10.04.2018.
        /// </summary>
        public static string ActualInfo {
            get {
                return ResourceManager.GetString("ActualInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUALLY TO.
        /// </summary>
        public static string ActuallyToUpperCase {
            get {
                return ResourceManager.GetString("ActuallyToUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the answer is ready, you will receive a notification..
        /// </summary>
        public static string AnswerReady {
            get {
                return ResourceManager.GetString("AnswerReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle information, data from 2013.
        /// </summary>
        public static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliably serves your interests..
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAND.
        /// </summary>
        public static string BrandUpperCase {
            get {
                return ResourceManager.GetString("BrandUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL VEHICLE.
        /// </summary>
        public static string ByPolandNumberUpperCase {
            get {
                return ResourceManager.GetString("ByPolandNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA VEHICLE.
        /// </summary>
        public static string ByUkraineNumberUpperCase {
            get {
                return ResourceManager.GetString("ByUkraineNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATE.
        /// </summary>
        public static string CalculateUppercase {
            get {
                return ResourceManager.GetString("CalculateUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PHONE NUMBER.
        /// </summary>
        public static string ChangePhoneNumberUpperCase {
            get {
                return ResourceManager.GetString("ChangePhoneNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil liability insurance.
        /// </summary>
        public static string CivilLiabilityInsurance {
            get {
                return ResourceManager.GetString("CivilLiabilityInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        public static string ConfirmPasswordUpperCase {
            get {
                return ResourceManager.GetString("ConfirmPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curb weight.
        /// </summary>
        public static string CurbWeight {
            get {
                return ResourceManager.GetString("CurbWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY.
        /// </summary>
        public static string CurrencyUppercase {
            get {
                return ResourceManager.GetString("CurrencyUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs clearance calculator for 2019.
        /// </summary>
        public static string CustomsClearanceCalculator {
            get {
                return ResourceManager.GetString("CustomsClearanceCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION DATE.
        /// </summary>
        public static string DataRegUpperCase {
            get {
                return ResourceManager.GetString("DataRegUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY / MONTH / YEAR.
        /// </summary>
        public static string DateHelpUpperCase {
            get {
                return ResourceManager.GetString("DateHelpUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF CREATION.
        /// </summary>
        public static string DateOfCreationUppercase {
            get {
                return ResourceManager.GetString("DateOfCreationUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string DateUpperCase {
            get {
                return ResourceManager.GetString("DateUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date vehicle record document issued.
        /// </summary>
        public static string DateVehicleRecordDocumentIssued {
            get {
                return ResourceManager.GetString("DateVehicleRecordDocumentIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date сurrent vehicle registration 
        ///certificate issued.
        /// </summary>
        public static string DateСurrentVehicleRegistrationCertificateIssued {
            get {
                return ResourceManager.GetString("DateСurrentVehicleRegistrationCertificateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day/month/year.
        /// </summary>
        public static string DayMonthYear {
            get {
                return ResourceManager.GetString("DayMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY.
        /// </summary>
        public static string DayUpperCase {
            get {
                return ResourceManager.GetString("DayUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailUppercase {
            get {
                return ResourceManager.GetString("EmailUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string EngineCapacity {
            get {
                return ResourceManager.GetString("EngineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE CAPACITY.
        /// </summary>
        public static string EngineCapacityUpperСase {
            get {
                return ResourceManager.GetString("EngineCapacityUpperСase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine power.
        /// </summary>
        public static string EnginePower {
            get {
                return ResourceManager.GetString("EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE TYPE.
        /// </summary>
        public static string EngineTypeUppercase {
            get {
                return ResourceManager.GetString("EngineTypeUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine capacity.
        /// </summary>
        public static string EngineСapacity {
            get {
                return ResourceManager.GetString("EngineСapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your birthday.
        /// </summary>
        public static string EnterBirthday {
            get {
                return ResourceManager.GetString("EnterBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER CURRENT PASSWORD.
        /// </summary>
        public static string EnterCurrentPasswordUpperCase {
            get {
                return ResourceManager.GetString("EnterCurrentPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER NAME.
        /// </summary>
        public static string EnterNameUpperCase {
            get {
                return ResourceManager.GetString("EnterNameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER NEW PASSWORD.
        /// </summary>
        public static string EnterNewPasswordUpperCase {
            get {
                return ResourceManager.GetString("EnterNewPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER PASSWORD.
        /// </summary>
        public static string EnterPasswordUpperCase {
            get {
                return ResourceManager.GetString("EnterPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection.
        /// </summary>
        public static string ERROR_INTERNET_CONNECTION {
            get {
                return ResourceManager.GetString("ERROR_INTERNET_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of 50 characters.
        /// </summary>
        public static string ERROR_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERROR_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of 2 characters.
        /// </summary>
        public static string ERROR_MINLENGTH {
            get {
                return ResourceManager.GetString("ERROR_MINLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ErrorUpperCase {
            get {
                return ResourceManager.GetString("ErrorUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTED.
        /// </summary>
        public static string ExecutedUpperCase {
            get {
                return ResourceManager.GetString("ExecutedUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISHED.
        /// </summary>
        public static string FinishedUpperCase {
            get {
                return ResourceManager.GetString("FinishedUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First registration date.
        /// </summary>
        public static string FirstRegistrationDateUppercase {
            get {
                return ResourceManager.GetString("FirstRegistrationDateUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full weight.
        /// </summary>
        public static string FullWeight {
            get {
                return ResourceManager.GetString("FullWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a reduction coefficient of 0.50 is applied to the excise duty when the vehicle is cleared for 90 days after the entry into force of the law 8487.
        /// </summary>
        public static string GracePeriodDescription {
            get {
                return ResourceManager.GetString("GracePeriodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY OF REQUESTS.
        /// </summary>
        public static string HistoryRequestsUpperCase {
            get {
                return ResourceManager.GetString("HistoryRequestsUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date format.
        /// </summary>
        public static string IncorrectDateFormat {
            get {
                return ResourceManager.GetString("IncorrectDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (IN DEVELOPMENT).
        /// </summary>
        public static string InDev {
            get {
                return ResourceManager.GetString("InDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER DATE.
        /// </summary>
        public static string InserDateUpperCase {
            get {
                return ResourceManager.GetString("InserDateUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER VIN.
        /// </summary>
        public static string InserVinUpperCase {
            get {
                return ResourceManager.GetString("InserVinUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string LanguageUpperCase {
            get {
                return ResourceManager.GetString("LanguageUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last recorded odometer reading.
        /// </summary>
        public static string LastRecordedOdometerReading {
            get {
                return ResourceManager.GetString("LastRecordedOdometerReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE TRANSPORT REGISTER.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max laden mass of braked trailer.
        /// </summary>
        public static string MaximumLadenMassOfBrakedTrailer {
            get {
                return ResourceManager.GetString("MaximumLadenMassOfBrakedTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max laden mass of unbraked trailer.
        /// </summary>
        public static string MaximumLadenMassOfUnbrakedTrailer {
            get {
                return ResourceManager.GetString("MaximumLadenMassOfUnbrakedTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max permissible towable mass.
        /// </summary>
        public static string MaximumPermissibleTowableMass {
            get {
                return ResourceManager.GetString("MaximumPermissibleTowableMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDDLE NAME.
        /// </summary>
        public static string MiddleNameUpperCase {
            get {
                return ResourceManager.GetString("MiddleNameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL.
        /// </summary>
        public static string ModelUpperCase {
            get {
                return ResourceManager.GetString("ModelUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTH.
        /// </summary>
        public static string MonthUpperCase {
            get {
                return ResourceManager.GetString("MonthUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NameUpperCase {
            get {
                return ResourceManager.GetString("NameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW POST.
        /// </summary>
        public static string NewPostUpperCase {
            get {
                return ResourceManager.GetString("NewPostUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string NewsUpperCase {
            get {
                return ResourceManager.GetString("NewsUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (IN DEVELOPING. IN THE NEXT VERSION).
        /// </summary>
        public static string NextVersionUpperCase {
            get {
                return ResourceManager.GetString("NextVersionUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account?.
        /// </summary>
        public static string NoAcc {
            get {
                return ResourceManager.GetString("NoAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive need access to your photo library to upload user photo.
        /// </summary>
        public static string NSPhotoLibraryUsageDescription {
            get {
                return ResourceManager.GetString("NSPhotoLibraryUsageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of axles.
        /// </summary>
        public static string NumberOfAxles {
            get {
                return ResourceManager.GetString("NumberOfAxles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats.
        /// </summary>
        public static string NumberOfSeats {
            get {
                return ResourceManager.GetString("NumberOfSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER.
        /// </summary>
        public static string NumberUpperCase {
            get {
                return ResourceManager.GetString("NumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string PasswordUpperCase {
            get {
                return ResourceManager.GetString("PasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDIVIDUAL.
        /// </summary>
        public static string PersonUpperCase {
            get {
                return ResourceManager.GetString("PersonUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT PHONE  NUMBER.
        /// </summary>
        public static string PhoneNumberUpperCase {
            get {
                return ResourceManager.GetString("PhoneNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NUMBER.
        /// </summary>
        public static string PhoneUpperCase {
            get {
                return ResourceManager.GetString("PhoneUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTO.
        /// </summary>
        public static string PhotoUpperCase {
            get {
                return ResourceManager.GetString("PhotoUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NUMBER.
        /// </summary>
        public static string PnoneNumberUpperCase {
            get {
                return ResourceManager.GetString("PnoneNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post with photo.
        /// </summary>
        public static string PostWithPhoto {
            get {
                return ResourceManager.GetString("PostWithPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST WITH PHOTO.
        /// </summary>
        public static string PostWithPhotoUpperCase {
            get {
                return ResourceManager.GetString("PostWithPhotoUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSING.
        /// </summary>
        public static string ProcessingUpperCase {
            get {
                return ResourceManager.GetString("ProcessingUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-entered password is incorrect.
        /// </summary>
        public static string ReEnteredPasswordIncorrect {
            get {
                return ResourceManager.GetString("ReEnteredPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards, Drive team.
        /// </summary>
        public static string Regards {
            get {
                return ResourceManager.GetString("Regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration status.
        /// </summary>
        public static string RegistrationStatus {
            get {
                return ResourceManager.GetString("RegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string RemoveUpperCase {
            get {
                return ResourceManager.GetString("RemoveUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been sent!.
        /// </summary>
        public static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVED.
        /// </summary>
        public static string SavedUpperCase {
            get {
                return ResourceManager.GetString("SavedUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH BY NUMBER.
        /// </summary>
        public static string SearchByNumber {
            get {
                return ResourceManager.GetString("SearchByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH CAR IN POLAND.
        /// </summary>
        public static string SearchByNumberFromPoland {
            get {
                return ResourceManager.GetString("SearchByNumberFromPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH CAR IN UKRAINE.
        /// </summary>
        public static string SearchByNumberFromUkraine {
            get {
                return ResourceManager.GetString("SearchByNumberFromUkraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual search.
        /// </summary>
        public static string SearchByPerson {
            get {
                return ResourceManager.GetString("SearchByPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH FOR A PHYSICAL PERSON.
        /// </summary>
        public static string SearchByPersonTitleUpperCase {
            get {
                return ResourceManager.GetString("SearchByPersonTitleUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH FOR A PHYSICAL PERSON.
        /// </summary>
        public static string SearchByPersonUpperCase {
            get {
                return ResourceManager.GetString("SearchByPersonUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH WAS NOT RESULT.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignInUpperCase {
            get {
                return ResourceManager.GetString("SignInUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURNAME.
        /// </summary>
        public static string SurnameUpperCase {
            get {
                return ResourceManager.GetString("SurnameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text post.
        /// </summary>
        public static string TextPost {
            get {
                return ResourceManager.GetString("TextPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total capacity.
        /// </summary>
        public static string TotalСapacity {
            get {
                return ResourceManager.GetString("TotalСapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try later.
        /// </summary>
        public static string TryLate {
            get {
                return ResourceManager.GetString("TryLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try using a higher quality image.
        /// </summary>
        public static string TryMore {
            get {
                return ResourceManager.GetString("TryMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSC.
        /// </summary>
        public static string TSC {
            get {
                return ResourceManager.GetString("TSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSC code.
        /// </summary>
        public static string TSCcode {
            get {
                return ResourceManager.GetString("TSCcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, access is limited.
        /// </summary>
        public static string UnauthorizeText {
            get {
                return ResourceManager.GetString("UnauthorizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information is constantly updated.
        /// </summary>
        public static string UpdatedInfo {
            get {
                return ResourceManager.GetString("UpdatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available to you..
        /// </summary>
        public static string UpdateVersionInfoPartOne {
            get {
                return ResourceManager.GetString("UpdateVersionInfoPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update!.
        /// </summary>
        public static string UpdateVersionInfoPartTwo {
            get {
                return ResourceManager.GetString("UpdateVersionInfoPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER NAME.
        /// </summary>
        public static string UserNameUpperCase {
            get {
                return ResourceManager.GetString("UserNameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLE AGE.
        /// </summary>
        public static string VehicleAgeUppercase {
            get {
                return ResourceManager.GetString("VehicleAgeUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLE COST.
        /// </summary>
        public static string VehicleCostUppercase {
            get {
                return ResourceManager.GetString("VehicleCostUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle found.
        /// </summary>
        public static string VehicleFound {
            get {
                return ResourceManager.GetString("VehicleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request give no results.
        /// </summary>
        public static string VehicleRequestGiveNoResults {
            get {
                return ResourceManager.GetString("VehicleRequestGiveNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLES.
        /// </summary>
        public static string VehiclesSecondTypeUpperCase {
            get {
                return ResourceManager.GetString("VehiclesSecondTypeUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLES.
        /// </summary>
        public static string VehiclesUpperCase {
            get {
                return ResourceManager.GetString("VehiclesUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle technical inspection.
        /// </summary>
        public static string VehicleTechnicalInspection {
            get {
                return ResourceManager.GetString("VehicleTechnicalInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF TRANSPORT.
        /// </summary>
        public static string VehicleTypeUppercase {
            get {
                return ResourceManager.GetString("VehicleTypeUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLE.
        /// </summary>
        public static string VehicleUpperCase {
            get {
                return ResourceManager.GetString("VehicleUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN CODE.
        /// </summary>
        public static string VINCodeUpperCase {
            get {
                return ResourceManager.GetString("VINCodeUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        public static string VinUppercase {
            get {
                return ResourceManager.GetString("VinUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight without load.
        /// </summary>
        public static string WeightWithoutLoad {
            get {
                return ResourceManager.GetString("WeightWithoutLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH GRACE PERIOD INTO ACCOUNT.
        /// </summary>
        public static string WithGracePeriodIntoAccountUppercase {
            get {
                return ResourceManager.GetString("WithGracePeriodIntoAccountUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of creation.
        /// </summary>
        public static string YearOfCreation {
            get {
                return ResourceManager.GetString("YearOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        public static string YearUpperCase {
            get {
                return ResourceManager.GetString("YearUpperCase", resourceCulture);
            }
        }
    }
}
