//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drive.Client.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drive.Client.Resources.Resx.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual information as of 10.04.2018.
        /// </summary>
        public static string ActualInfo {
            get {
                return ResourceManager.GetString("ActualInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliably serves your interests..
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY NUMBER.
        /// </summary>
        public static string ByNumberUpperCase {
            get {
                return ResourceManager.GetString("ByNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PHONE NUMBER.
        /// </summary>
        public static string ChangePhoneNumberUpperCase {
            get {
                return ResourceManager.GetString("ChangePhoneNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        public static string ConfirmPasswordUpperCase {
            get {
                return ResourceManager.GetString("ConfirmPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailUppercase {
            get {
                return ResourceManager.GetString("EmailUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string EngineCapacity {
            get {
                return ResourceManager.GetString("EngineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER CURRENT PASSWORD.
        /// </summary>
        public static string EnterCurrentPasswordUpperCase {
            get {
                return ResourceManager.GetString("EnterCurrentPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER NAME.
        /// </summary>
        public static string EnterNameUpperCase {
            get {
                return ResourceManager.GetString("EnterNameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER NEW PASSWORD.
        /// </summary>
        public static string EnterNewPasswordUpperCase {
            get {
                return ResourceManager.GetString("EnterNewPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER PASSWORD.
        /// </summary>
        public static string EnterPasswordUpperCase {
            get {
                return ResourceManager.GetString("EnterPasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection.
        /// </summary>
        public static string ERROR_INTERNET_CONNECTION {
            get {
                return ResourceManager.GetString("ERROR_INTERNET_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full weight.
        /// </summary>
        public static string FullWeight {
            get {
                return ResourceManager.GetString("FullWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (IN DEVELOPMENT).
        /// </summary>
        public static string InDev {
            get {
                return ResourceManager.GetString("InDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string LanguageUpperCase {
            get {
                return ResourceManager.GetString("LanguageUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE TRANSPORT REGISTER.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NameUpperCase {
            get {
                return ResourceManager.GetString("NameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW POST.
        /// </summary>
        public static string NewPostUpperCase {
            get {
                return ResourceManager.GetString("NewPostUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string NewsUpperCase {
            get {
                return ResourceManager.GetString("NewsUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (IN THE NEXT VERSION).
        /// </summary>
        public static string NextVersionUpperCase {
            get {
                return ResourceManager.GetString("NextVersionUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account?.
        /// </summary>
        public static string NoAcc {
            get {
                return ResourceManager.GetString("NoAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string PasswordUpperCase {
            get {
                return ResourceManager.GetString("PasswordUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDIVIDUAL.
        /// </summary>
        public static string PersonUpperCase {
            get {
                return ResourceManager.GetString("PersonUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT PHONE  NUMBER.
        /// </summary>
        public static string PhoneNumberUpperCase {
            get {
                return ResourceManager.GetString("PhoneNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NUMBER.
        /// </summary>
        public static string PhoneUpperCase {
            get {
                return ResourceManager.GetString("PhoneUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NUMBER.
        /// </summary>
        public static string PnoneNumberUpperCase {
            get {
                return ResourceManager.GetString("PnoneNumberUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-entered password is incorrect.
        /// </summary>
        public static string ReEnteredPasswordIncorrect {
            get {
                return ResourceManager.GetString("ReEnteredPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVED.
        /// </summary>
        public static string SavedUpperCase {
            get {
                return ResourceManager.GetString("SavedUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH FOR NUMBERS.
        /// </summary>
        public static string SearchByNumber {
            get {
                return ResourceManager.GetString("SearchByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH FOR A PHYSICAL PERSON.
        /// </summary>
        public static string SearchByPersonUpperCase {
            get {
                return ResourceManager.GetString("SearchByPersonUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignInUpperCase {
            get {
                return ResourceManager.GetString("SignInUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSC.
        /// </summary>
        public static string TSC {
            get {
                return ResourceManager.GetString("TSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSC code.
        /// </summary>
        public static string TSCcode {
            get {
                return ResourceManager.GetString("TSCcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER NAME.
        /// </summary>
        public static string UserNameUpperCase {
            get {
                return ResourceManager.GetString("UserNameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight without load.
        /// </summary>
        public static string WeightWithoutLoad {
            get {
                return ResourceManager.GetString("WeightWithoutLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of creation.
        /// </summary>
        public static string YearOfCreation {
            get {
                return ResourceManager.GetString("YearOfCreation", resourceCulture);
            }
        }
    }
}
